### PR TITLE
Issue 6630 - Add Test Groups tab

### LINKED ISSUE #6630: Support filtering tasks by *manifest* (not test path) path from selected task
(I split up this issue to *only* show manifests/groups of tests instead of test paths since it is a lot more work)

Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1636506
UI proving the concept: https://test-paths-for-task.netlify.app

The following mock-up allows the developers/sheriffs to see what manifests and test paths executed for a given task. Each listed manifest/test path is a link to the existing view that filters all tasks that executed the same manifest/test path.

This solves the problem where a developer/sheriff would look for a failed test path from the logs copy it and use some dropdowns from the UI to filter tasks that have executed the same manifest or test path.

image

### PR DESCRIPTION
**Pull request by armenzg**
Fixes #6630

When selecting a job that has MOZHARNESS_TEST_PATH specified we can fetch
what test groups[1] were executed.

This change adds a new tab named "Test Groups" and renames "Job Details" to "Artifacts".

[1] Some test jobs use manifests to group tests while wpt jobs don't use manifests.

### CODE REVIEW

**Comment by armenzg** [comment]
Some test jobs have "Test Groups" (for instance wpt, xpcshell and mochitests)

image

**Comment by armenzg** [comment]
I noticed a small bug. I will flag for review next week.

File: ui/job-view/details/DetailsPanel.jsx [hunk 1]
```diff
@@ -173,6 +180,7 @@ class DetailsPanel extends React.Component {
           phSeriesPromise,
           jobArtifactsPromise,
           builtFromArtifactPromise,
+          taskDefinitionPromise,
```
Comment (armenzg) [inline ui/job-view/details/DetailsPanel.jsx:183]: Hi @camd 
Adding the extra promise in here makes one of the Selenium tests to time out.
Before this test failed I noticed on Friday this pattern.

I believe a better pattern is to mark a tab as disabled and then let the component within that tab notify the parent TabsPanel.

In this PR, I changed the model and it fixes the test:
https://github.com/mozilla/treeherder/pull/6645

**Comment by armenzg** [comment]
Hi @camd 
I prefer this latter approach because it prototypes how to break away from the big Promise.all() and makes the `JobTestGroups` decoupled from `TabsPanel`.

This change moves away from the approach of *not* including a Tab to *disabling* a tab by default and enabling it once the data loads.

When you load a job without `MOZHARNESS_TEST_PATH` you will "Test Groups" in italics and cannot be clicked:
image

If you click on a job that has that env variable defined you will briefly see the tab as disabled, however, it quickly gets enabled. You can see below how the tab is *not* in italics:
image

Clicking "Test groups" will show the following:
image

File: ui/css/treeherder-details-panel.css [hunk 2]
```diff
@@ -134,6 +134,12 @@ div#details-panel-content .actionbar-nav > li > button:focus {
 
 .react-tabs__tab-panel--selected {
   height: 100%;
+  margin: 0.5em 1em;
+  overflow-y: auto;
+}
+
+.react-tabs__tab--disabled {
```
Comment (camd) [inline ui/css/treeherder-details-panel.css:141]: There is a property `disabledTabClassName` that might work instead of doing this custom.

https://www.npmjs.com/package/react-tabs#disabledtabclassname-string

Comment (camd) [reply ui/css/treeherder-details-panel.css:141]: Also for selected: `selectedTabClassName`

I know the `react-tabs__tab-panel--selected` class was already there.  Up to you if it's easier to use these props.

Comment (armenzg) [reply ui/css/treeherder-details-panel.css:141]: If I read the documentation correctly, I'm actually not doing it custom since the default of that property is `react-tabs__tab--disabled`. Using the property `disabledTabClassName` is for defining something custom.

Comment (armenzg) [reply ui/css/treeherder-details-panel.css:141]: For instance `react-tabs__tab--selected` is the default value and is in use when inspecting the element.
image

I hope I'm not misunderstanding!

Comment (camd) [reply ui/css/treeherder-details-panel.css:141]: I think this is fine.  I believe the difference is that having our CSS do this means it will apply to all `react-tabs` that we have in TH.  We only have 1, so that's fine.  :) If we had multiple and wanted them to be different, using a custom class with the props they provide would allow us to do that.

**Comment by sarah-clements** [comment]
> Hi @camd
> I prefer this latter approach because it prototypes how to break away from the big Promise.all() and makes the `JobTestGroups` decoupled from `TabsPanel`.
> 
> This change moves away from the approach of _not_ including a Tab to _disabling_ a tab by default and enabling it once the data loads.
> 
> When you load a job without `MOZHARNESS_TEST_PATH` you will "Test Groups" in italics and cannot be clicked:
> image
> 
> If you click on a job that has that env variable defined you will briefly see the tab as disabled, however, it quickly gets enabled. You can see below how the tab is _not_ in italics:
> image
> 
> Clicking "Test groups" will show the following:
> image

Per the meeting, the meaning of this is a little ambiguous (my first thought was what are "test groups"). Having an info icon next to Test groups or text in parenthesis explaining what it does might make the purpose of this feature more apparent. :)
