### PR TITLE
Bug 1609211 - Persist settings in URL

### LINKED ISSUE #6226: Persist settings in URL:
https://bugzilla.mozilla.org/show_bug.cgi?id=1609211

### PR DESCRIPTION
**Pull request by SuyashSalampuria**
Fixes #6226 

- [x]  Order By changes persist in the URL
- [x] Group By changes persist in the URL
- [x]  Metrics changes persist in the URL

### CODE REVIEW

**Comment by SuyashSalampuria** [comment]
@sarah-clements @camd Could you give your initial reviews if this is the expected way
I am trying to find the best way to persisit metrics too in the URL

File: ui/push-health/TestMetric.jsx [hunk 1]
```diff
@@ -85,4 +101,23 @@ TestMetric.propTypes = {
...
+  setKnownIssuesOrderBy: PropTypes.func,
+  setKnownIssuesGroupBy: PropTypes.func,
+};
+
+TestMetric.defaultProps = {
+  regressionsOrderBy: 'count',
+  regressionsGroupBy: 'path',
+  knownIssuesOrderBy: 'count',
+  knownIssuesGroupBy: 'path',
+  setRegressionsOrderBy: () => {},
```
Comment (sarah-clements) [inline ui/push-health/TestMetric.jsx:119]: This should be a required prop.

File: ui/push-health/Health.jsx [hunk 2]
```diff
@@ -87,6 +91,50 @@ export default class Health extends React.PureComponent {
...
+  setKnownIssuesGroupBy = (knownIssuesGroupBy) => {
+    const { location, history } = this.props;
+    const newParams = {
+      ...parseQueryParams(location.search),
+      knownIssuesGroupBy,
+    };
+    const queryString = createQueryParams(newParams);
+    updateQueryParams(queryString, history, location);
+    this.setState({ knownIssuesGroupBy });
+  };
```
Comment (sarah-clements) [inline ui/push-health/Health.jsx:136]: You're on the right track here, but since all of this logic is the same you should create one generic function that accepts an argument for the state that should be updated (there is a way to do this without entering a specific state name/key). I suggest naming it something like `updateParamsAndState`.

Comment (SuyashSalampuria) [reply ui/push-health/Health.jsx:136]: I was facing the problem of updating the state variable from a generic function
I mean, how do I come to know which state variable ```regressionsGroupBy``` or ```knownIssuesOrderBy``` is to be changed
Other things will be surely much better to handle in a generic function

**Comment by sarah-clements** [comment]
> @sarah-clements @camd Could you give your initial reviews if this is the expected way
> I am trying to find the best way to persisit metrics too in the URL

I would look at what the minimum amount of data that is needed in order to call the failure summary API for a selected task. You'll also need a query string/param that will tell the task component to be open instead of collapsed.

File: ui/push-health/Health.jsx (hunk 2 above)
Comment (sarah-clements) [reply ui/push-health/Health.jsx:136]: There is a way to solve this problem, you just need to research it :)

Comment (sarah-clements) [reply ui/push-health/Health.jsx:136]: It is better to find a DRY solution - here you are repeating the same code multiple times. So there are a few different approaches you can take that would be better.

Comment (SuyashSalampuria) [reply ui/push-health/Health.jsx:136]: I am unable to find a good solution to it.
The only way I find is to pass a string parameter from the classification group component to see which state variable has to be changed. Does this method work?

Comment (sarah-clements) [reply ui/push-health/Health.jsx:136]: An easy solution is to pass an object parameter instead of a variable: `this.setState(stateObj)`. Another one would be to call setState inline in the onClick and update the query parameters as a callback function.

Comment (sarah-clements) [reply ui/push-health/Health.jsx:136]: You could pass in a string, but then you'd need a value unless you were doing a boolean toogle, so: `(stateName, value) => this.setState({ [stateName]: value }). This is possible by using computed property names.

**Comment by SuyashSalampuria** [comment]
@camd  I have facing a problem in persist the exact task inside the exact group
I am currently using the task id to see which group should be expanded
But, the tasks are not unique and several group may have same task
Should I add the testName also to the URL so that we can see can make it unique.This would make the URL very long although
I have already added the 2 params

1. defaultExpandedTab - whether possible regressions is expanded or known issues
2. expandedDefaultMetric - This contains the task id to show the details panel

The things seem to be working fine except that many tests are expanded

**Comment by camd** [comment]
> @camd I have facing a problem in persist the exact task inside the exact group
> I am currently using the task id to see which group should be expanded
> But, the tasks are not unique and several group may have same task
> Should I add the testName also to the URL so that we can see can make it unique.This would make the URL very long although
> I have already added the 2 params
> 
>     1. defaultExpandedTab - whether possible regressions is expanded or known issues
> 
>     2. expandedDefaultMetric - This contains the task id to show the details panel
> 
> 
> The things seem to be working fine except that many tests are expanded

One way to do this would be to add the `id` of the `test` from the `FailureLine` table in this `for` loop:
https://github.com/mozilla/treeherder/blob/ed3913ad0d34a63fc324312ab8fd5d50c18ddaab/treeherder/push_health/tests.py#L96

That way you could just use the `id` instead of the test name.  The unit tests should ensure these things work.  

When we move to using `mozci` as a back-end, some of these things will likely change.  So the `id`s we get for this may be different after that change.  But that's ok.  There is not a wide use-base yet.  And we can break backward compatibility at that time if we need to.

**Comment by SuyashSalampuria** [comment]
@camd  Please review this too .
I currently need 4 variables on the params to expand the correct task on the correct test
Please suggest if you can find a better solution too

File: ui/push-health/PlatformConfig.jsx [hunk 3]
```diff
@@ -22,12 +22,28 @@ class PlatformConfig extends React.PureComponent {
...
+    }
+  }
+
   setSelectedTask = (task) => {
     const { selectedTask } = this.state;
 
     if (selectedTask === task || !task) {
       this.setState({ selectedTask: null, detailsShowing: false });
     } else {
+      this.props.updateParamsAndState({ expandedDefaultMetric: task.id });
```
Comment (camd) [inline ui/push-health/PlatformConfig.jsx:46]: A `metric` is different than a `task`.  I think this `state` name should be `selectedTask`.  Or you could use `selectedTaskId` for the querystring param name.

`metric`would be either `tests`, `builds` or `linting`.  And we should persist that, too.

The url params are seeming a bit verbose to me.  I'm wondering about something closer to this:

`selectedTask` = `task.id`
`test`= `test.id` (rather than the full test text)
`testgroup` = one of `pr`(possible regressions), `ki` (known issues)
`metric` = one of `tests`, `linting`, or `builds`

It also seems worthwhile to add these settings to the URL as you expand each one.  You may not want to necessarily share just a selected task, but an expanded list of tests in one area.

Those names might seem a bit generic for being part of `state`.  Perhaps `selectedTest`, `selectedTestGroup`, etc would be fine.

Comment (SuyashSalampuria) [reply ui/push-health/PlatformConfig.jsx:46]: > metricwould be either tests, builds or linting. And we should persist that, too.

I think we can have that without persisting it on the URL. If any of the params, that have been added in this PR is present, tests should be shown by default. The cost of this would be checking max 7 conditions on the React code

> test= test.id (rather than the full test text)

The tests are actually grouped by path or platform. So under any tests object in the frontend(which can be expanded or collapse), there are several tests from different failure lines. 
Screenshot from 2020-08-05 21-06-08
This is the screenshot of the props in the Test Component. the ```test``` object may have more than one tests from different failure lines, hence different   ```failure.id```. This was my understanding from the code. Please rectify me if I am wrong or we have store the id which has the whole test name in the URL

**Comment by SuyashSalampuria** [comment]
@camd I just wanted to confirm if we are adding test group to the URL or the current way is fine

File: ui/push-health/PlatformConfig.jsx (hunk 3 above)
Comment (camd) [reply ui/push-health/PlatformConfig.jsx]: > This is the screenshot of the props in the Test Component. the `test` object may have more than one tests from different failure lines, hence different `failure.id`. This was my understanding from the code. Please rectify me if I am wrong or we have to store the id which has the whole test name in the URL

Ahh yes.  I see what you mean.  That ID won't be consistent, especially if some of the back-end data changes and a task is moved to "known issues" because retriggers come back with more passing than failing.

OK, let's go with the text, then.  I'll test this locally a bit today and see if I can find any issues.  But this is looking good.  :)

**Comment by camd** [comment]
When I use this url: http://localhost:5000/pushhealth.html?repo=try&revision=7b971f5053efbca154a3e3232a85328eb8cd376f&selectedTaskId=312757448&selectedTest=linux1804-64debug&testGroup=pr&regressionsGroupBy=platform

It opens ALL of the tasks on that platform.  So I think it needs to also persist the `job_type_name` in the url.

**Comment by camd** [comment]
Also, it should save when things are only partially expanded.  Not only when a task has been selected.  It if we are in this state, it should just open to here:

Screen Shot 2020-08-11 at 2 20 27 PM

**Comment by camd** [comment]
> @camd I just wanted to confirm if we are adding test group to the URL or the current way is fine

It looks like you have added `testGroup=pr` to the url.  I think this is good.  Or were you asking about something else?

**Comment by SuyashSalampuria** [comment]
> It looks like you have added testGroup=pr to the url. I think this is good. Or were you asking about something else?
Hey @camd
We have some many groupings there. I was speaking of selectedTest=linux1804-64debug , here actually
I have made some  changes 
It would be great if you could review it once again

File: ui/push-health/Test.jsx [hunk 4]
```diff
@@ -18,14 +18,30 @@ class Test extends PureComponent {
...
     this.setState({ clipboardVisible: key });
   };
 
   toggleDetails = () => {
-    this.setState((prevState) => ({
-      detailsShowing: !prevState.detailsShowing,
-    }));
+    let { detailsShowing } = this.state;
+    const { updateParamsAndState, test } = this.props;
+    detailsShowing = !detailsShowing;
```
Comment (camd) [inline ui/push-health/Test.jsx:35]: blank line after `const`
